[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/availability"
  to = "/.netlify/functions/availability"
  status = 200

[[redirects]]
  from = "/api/reservations"
  to = "/.netlify/functions/reservations"
  status = 200

[[redirects]]
  from = "/api/admin/login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin/reservations"
  to = "/.netlify/functions/admin-reservations"
  status = 200

[[redirects]]
  from = "/api/admin/reservation"
  to = "/.netlify/functions/admin-reservation"
  status = 200

[[redirects]]
  from = "/api/admin/tables"
  to = "/.netlify/functions/admin-tables"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/admin/events"
  to = "/.netlify/functions/admin-events"
  status = 200

[[redirects]]
  from = "/api/admin/settings"
  to = "/.netlify/functions/admin-settings"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
